import * as exercises from "./exercises";
import { showContent } from "./exercises/utils";

showContent(1, exercises.exercise1("Dani"));
showContent(2, exercises.exercise2(7));
showContent(3, exercises.exercise3(10));
showContent(4, exercises.exercise4("Hll, m lrnng jvscrpt"));
showContent(5, exercises.exercise5());
showContent(6, exercises.exercise6());
showContent(7, exercises.exercise7());
showContent(8, exercises.exercise8());
showContent(9, exercises.exercise9());
showContent(10, exercises.exercise10());
showContent(11, exercises.exercise11());
showContent(12, exercises.exercise12());
showContent(13, exercises.exercise13());
showContent(14, exercises.exercise14());
showContent(15, exercises.exercise15());
showContent(16, exercises.exercise16());
showContent(17, exercises.exercise17());
showContent(18, exercises.exercise18());
showContent(19, exercises.exercise19());
showContent(20, exercises.exercise20());
